// Real ports and air hubs. The AI picks an id from this list, and the server fills in
// the name, country and coordinates itself, so a port can never be invented or misplaced.
// [id, name, country, lat, lng, type]
const RAW = [
  // East Asia
  ["cn-shanghai", "Port of Shanghai", "China", 31.23, 121.49, "port"],
  ["cn-ningbo", "Ningbo-Zhoushan Port", "China", 29.87, 121.88, "port"],
  ["cn-shenzhen", "Yantian Port, Shenzhen", "China", 22.57, 114.28, "port"],
  ["cn-guangzhou", "Nansha Port, Guangzhou", "China", 22.75, 113.6, "port"],
  ["cn-qingdao", "Port of Qingdao", "China", 36.07, 120.32, "port"],
  ["cn-tianjin", "Port of Tianjin", "China", 38.98, 117.75, "port"],
  ["hk-hong-kong", "Port of Hong Kong", "Hong Kong", 22.3, 114.17, "port"],
  ["tw-kaohsiung", "Port of Kaohsiung", "Taiwan", 22.61, 120.28, "port"],
  ["kr-busan", "Port of Busan", "South Korea", 35.1, 129.04, "port"],
  ["jp-yokohama", "Port of Yokohama", "Japan", 35.45, 139.65, "port"],
  ["jp-kobe", "Port of Kobe", "Japan", 34.68, 135.2, "port"],
  // South and South-East Asia
  ["sg-singapore", "Port of Singapore", "Singapore", 1.26, 103.84, "port"],
  ["my-port-klang", "Port Klang", "Malaysia", 3.0, 101.39, "port"],
  ["my-tanjung-pelepas", "Port of Tanjung Pelepas", "Malaysia", 1.36, 103.55, "port"],
  ["th-laem-chabang", "Laem Chabang Port", "Thailand", 13.08, 100.88, "port"],
  ["vn-hai-phong", "Port of Hai Phong", "Vietnam", 20.85, 106.77, "port"],
  ["vn-ho-chi-minh", "Cat Lai Port, Ho Chi Minh City", "Vietnam", 10.76, 106.79, "port"],
  ["id-tanjung-priok", "Tanjung Priok, Jakarta", "Indonesia", -6.1, 106.88, "port"],
  ["id-surabaya", "Port of Surabaya", "Indonesia", -7.2, 112.73, "port"],
  ["ph-manila", "Port of Manila", "Philippines", 14.59, 120.96, "port"],
  ["in-nhava-sheva", "Nhava Sheva (JNPT), Mumbai", "India", 18.95, 72.95, "port"],
  ["in-mundra", "Mundra Port", "India", 22.74, 69.7, "port"],
  ["in-chennai", "Port of Chennai", "India", 13.09, 80.3, "port"],
  ["in-kochi", "Port of Kochi", "India", 9.97, 76.26, "port"],
  ["lk-colombo", "Port of Colombo", "Sri Lanka", 6.95, 79.85, "port"],
  ["bd-chittagong", "Port of Chattogram", "Bangladesh", 22.31, 91.8, "port"],
  ["pk-karachi", "Port of Karachi", "Pakistan", 24.84, 66.98, "port"],
  // Middle East and Africa
  ["ae-jebel-ali", "Jebel Ali Port, Dubai", "United Arab Emirates", 25.01, 55.06, "port"],
  ["om-salalah", "Port of Salalah", "Oman", 16.94, 54.01, "port"],
  ["sa-jeddah", "Jeddah Islamic Port", "Saudi Arabia", 21.48, 39.17, "port"],
  ["tr-mersin", "Port of Mersin", "Turkey", 36.8, 34.64, "port"],
  ["tr-ambarli", "Ambarli Port, Istanbul", "Turkey", 40.97, 28.69, "port"],
  ["il-haifa", "Port of Haifa", "Israel", 32.82, 35.0, "port"],
  ["il-ashdod", "Port of Ashdod", "Israel", 31.82, 34.64, "port"],
  ["eg-port-said", "Port Said", "Egypt", 31.26, 32.3, "port"],
  ["eg-alexandria", "Port of Alexandria", "Egypt", 31.19, 29.88, "port"],
  ["ma-tangier-med", "Tanger Med", "Morocco", 35.89, -5.5, "port"],
  ["sn-dakar", "Port of Dakar", "Senegal", 14.69, -17.43, "port"],
  ["ci-abidjan", "Port of Abidjan", "Ivory Coast", 5.3, -4.02, "port"],
  ["gh-tema", "Port of Tema", "Ghana", 5.62, 0.02, "port"],
  ["ng-apapa", "Apapa Port, Lagos", "Nigeria", 6.45, 3.36, "port"],
  ["ke-mombasa", "Port of Mombasa", "Kenya", -4.06, 39.67, "port"],
  ["tz-dar-es-salaam", "Port of Dar es Salaam", "Tanzania", -6.82, 39.29, "port"],
  ["za-durban", "Port of Durban", "South Africa", -29.87, 31.03, "port"],
  ["za-cape-town", "Port of Cape Town", "South Africa", -33.92, 18.43, "port"],
  // Europe
  ["gb-felixstowe", "Port of Felixstowe", "United Kingdom", 51.96, 1.35, "port"],
  ["gb-southampton", "Port of Southampton", "United Kingdom", 50.9, -1.42, "port"],
  ["gb-london-gateway", "London Gateway", "United Kingdom", 51.5, 0.5, "port"],
  ["gb-liverpool", "Port of Liverpool", "United Kingdom", 53.45, -3.02, "port"],
  ["gb-dover", "Port of Dover", "United Kingdom", 51.12, 1.32, "port"],
  ["ie-dublin", "Dublin Port", "Ireland", 53.35, -6.2, "port"],
  ["nl-rotterdam", "Port of Rotterdam", "Netherlands", 51.95, 4.14, "port"],
  ["be-antwerp", "Port of Antwerp-Bruges", "Belgium", 51.27, 4.38, "port"],
  ["de-hamburg", "Port of Hamburg", "Germany", 53.54, 9.97, "port"],
  ["de-bremerhaven", "Bremerhaven", "Germany", 53.55, 8.55, "port"],
  ["fr-le-havre", "Port of Le Havre", "France", 49.48, 0.11, "port"],
  ["fr-marseille", "Port of Marseille-Fos", "France", 43.33, 5.35, "port"],
  ["es-algeciras", "Port of Algeciras", "Spain", 36.13, -5.43, "port"],
  ["es-valencia", "Port of Valencia", "Spain", 39.44, -0.32, "port"],
  ["es-barcelona", "Port of Barcelona", "Spain", 41.35, 2.17, "port"],
  ["pt-sines", "Port of Sines", "Portugal", 37.95, -8.87, "port"],
  ["it-genoa", "Port of Genoa", "Italy", 44.41, 8.93, "port"],
  ["it-gioia-tauro", "Gioia Tauro", "Italy", 38.44, 15.9, "port"],
  ["gr-piraeus", "Port of Piraeus", "Greece", 37.94, 23.63, "port"],
  ["pl-gdansk", "Port of Gdansk", "Poland", 54.4, 18.67, "port"],
  ["se-gothenburg", "Port of Gothenburg", "Sweden", 57.69, 11.9, "port"],
  ["ee-muuga", "Muuga Harbour, Tallinn", "Estonia", 59.5, 24.96, "port"],
  ["lv-riga", "Port of Riga", "Latvia", 56.95, 24.1, "port"],
  // North America
  ["us-los-angeles", "Ports of Los Angeles and Long Beach", "United States", 33.74, -118.26, "port"],
  ["us-oakland", "Port of Oakland", "United States", 37.8, -122.3, "port"],
  ["us-seattle", "Port of Seattle-Tacoma", "United States", 47.58, -122.35, "port"],
  ["us-new-york", "Port of New York and New Jersey", "United States", 40.67, -74.04, "port"],
  ["us-savannah", "Port of Savannah", "United States", 32.08, -81.09, "port"],
  ["us-charleston", "Port of Charleston", "United States", 32.78, -79.93, "port"],
  ["us-houston", "Port of Houston", "United States", 29.73, -95.27, "port"],
  ["us-miami", "PortMiami", "United States", 25.77, -80.17, "port"],
  ["ca-vancouver", "Port of Vancouver", "Canada", 49.29, -123.11, "port"],
  ["ca-montreal", "Port of Montreal", "Canada", 45.5, -73.55, "port"],
  ["mx-manzanillo", "Port of Manzanillo", "Mexico", 19.05, -104.32, "port"],
  ["mx-lazaro-cardenas", "Port of Lazaro Cardenas", "Mexico", 17.96, -102.18, "port"],
  // Central and South America
  ["pa-balboa", "Balboa, Panama", "Panama", 8.95, -79.57, "port"],
  ["pa-colon", "Colon, Panama", "Panama", 9.36, -79.9, "port"],
  ["cr-limon", "Puerto Limon", "Costa Rica", 9.99, -83.03, "port"],
  ["gt-puerto-quetzal", "Puerto Quetzal", "Guatemala", 13.93, -90.78, "port"],
  ["co-cartagena", "Port of Cartagena", "Colombia", 10.41, -75.53, "port"],
  ["ec-guayaquil", "Port of Guayaquil", "Ecuador", -2.28, -79.9, "port"],
  ["pe-callao", "Port of Callao", "Peru", -12.05, -77.15, "port"],
  ["cl-san-antonio", "Port of San Antonio", "Chile", -33.59, -71.61, "port"],
  ["cl-valparaiso", "Port of Valparaiso", "Chile", -33.04, -71.63, "port"],
  ["br-santos", "Port of Santos", "Brazil", -23.96, -46.3, "port"],
  ["br-paranagua", "Port of Paranagua", "Brazil", -25.5, -48.52, "port"],
  ["ar-buenos-aires", "Port of Buenos Aires", "Argentina", -34.6, -58.37, "port"],
  ["uy-montevideo", "Port of Montevideo", "Uruguay", -34.9, -56.21, "port"],
  // Oceania
  ["au-sydney", "Port Botany, Sydney", "Australia", -33.97, 151.21, "port"],
  ["au-melbourne", "Port of Melbourne", "Australia", -37.83, 144.92, "port"],
  ["au-brisbane", "Port of Brisbane", "Australia", -27.38, 153.17, "port"],
  ["au-fremantle", "Fremantle Port", "Australia", -32.06, 115.74, "port"],
  ["nz-tauranga", "Port of Tauranga", "New Zealand", -37.65, 176.17, "port"],
  ["nz-auckland", "Ports of Auckland", "New Zealand", -36.84, 174.77, "port"],
  // Air cargo hubs
  ["air-lhr", "London Heathrow Airport", "United Kingdom", 51.47, -0.45, "air"],
  ["air-ams", "Amsterdam Schiphol Airport", "Netherlands", 52.31, 4.76, "air"],
  ["air-fra", "Frankfurt Airport", "Germany", 50.04, 8.56, "air"],
  ["air-hkg", "Hong Kong International Airport", "Hong Kong", 22.31, 113.91, "air"],
  ["air-sin", "Singapore Changi Airport", "Singapore", 1.36, 103.99, "air"],
  ["air-nbo", "Nairobi Jomo Kenyatta Airport", "Kenya", -1.32, 36.93, "air"],
  ["air-bog", "Bogota El Dorado Airport", "Colombia", 4.7, -74.15, "air"],
  ["air-mia", "Miami International Airport", "United States", 25.8, -80.29, "air"],
  ["air-mem", "Memphis International Airport", "United States", 35.04, -89.98, "air"],
  ["air-dxb", "Dubai International Airport", "United Arab Emirates", 25.25, 55.36, "air"],
];

export const PORTS = Object.fromEntries(
  RAW.map(([id, name, country, lat, lng, type]) => [id, { id, name, country, lat, lng, type }])
);
export const PORT_IDS = Object.keys(PORTS);
